# 服务器配置
server:
  port: 35251 # 服务器端口
  servlet:
    context-path: /api # 应用上下文路径

# 春季框架相关配置
spring:
  flyway:
    #是否启用
    enabled: true
    url: jdbc:mysql://localhost:3306/yys_aivideo
    user: root
    password: config5566
    # 可以支持多个location, 用','隔开
    locations: classpath:db/migration
    #是否创建元数据表
    validate-on-migrate: true
    clean-disabled: true
    # 如果数据库不是空表，需要设置成 true，否则启动报错
    baseline-on-migrate: true
    # 版本控制日志表，默认flyway_schema_history,不同系统建议修改数据
    table: flyway_schema_history
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # 数据库驱动类名
    url: jdbc:mysql://localhost:3306/yys_aivideo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true # 数据库连接URL
    username: root # 数据库用户名
    password: config5566 # 数据库密码
    type: com.alibaba.druid.pool.DruidDataSource # 数据源类型，这里使用Druid
  rabbitmq:
    host: localhost # RabbitMQ主机
    port: 5672 # RabbitMQ端口
    username: guest # RabbitMQ用户名
    password: guest # RabbitMQ密码
  elasticsearch:
    uris: localhost:9222 # Elasticsearch地址
    socket-timeout: 30000ms # Socket超时时间
    connection-timeout: 1000ms # 连接超时时间
  redis:
    host: localhost # Redis主机
    port: 6379 # Redis端口

# 日志配置
logging:
  level:
    root: INFO # 根日志级别
    com.yys.util.JwtRequestFilter: DEBUG # JwtRequestFilter日志级别

# MyBatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case : true # 是否开启下划线到驼峰命名的转换

# 自定义配置
stream:
  python-url: http://localhost:5050 # Python服务URL
  minio:
    endpoint: http://localhost:9000
    access-key: admin
    secret-key: admin123
    imgbucket:
      name: training-img
upload:
  path: /path # 上传路径
  imgpath:
file:
  upload-dir: src/main/java/com/yys/zipdata # 文件上传目录
  uploaddir: upweights # Linux上传目录
  upload-img: src/main/java/com/yys/imgdata #